version: '3.8'

services:
  dbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: dbeaver
    ports:
      - "8978:8978"
    volumes:
      - cloudbeaver_data:/opt/cloudbeaver/workspace
    restart: unless-stopped

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: alex
      POSTGRES_PASSWORD: 2155
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 2155
      MYSQL_DATABASE: testdb
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
    restart: unless-stopped


volumes:
  pgdata:
  mysqldata:
  cloudbeaver_data:




